project_id = "local"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 6544

[studio]
enabled = true
port = 54323

[inbucket]
enabled = false
port = 54324

[auth]
site_url = "http://localhost:5174"
additional_redirect_urls = ["http://localhost:5173", "http://localhost:5174"]
enable_signup = true

[auth.external.google]
enabled = true
client_id = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET)"
redirect_uri = "http://127.0.0.1:54321/auth/v1/callback"

[storage]
enabled = true
file_size_limit = 52428800

[analytics]
enabled = false

[edge_runtime]
enabled = true

[functions]
[functions.send-email]
verify_jwt = false

[functions.pretix-sync]
verify_jwt = false
