project_id = "local"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 6544

[studio]
enabled = true
port = 54323

[inbucket]
enabled = false
port = 54324

[auth]
site_url = "http://localhost:54321"
additional_redirect_urls = ["http://localhost:5173"]

[storage]
enabled = true
file_size_limit = 52428800

[analytics]
enabled = false

[edge_runtime]
enabled = false

[functions]
[functions.unstable_features]
